server:
  context-path: /mangerSys
  jsp-servlet:
    init-parameters:
      development: true
#  address: 192.168.1.106
spring:
  profiles:
    active: prod
  mvc:
    view:
      prefix: /
      suffix: .jsp
  http:
    multipart:
      max-request-size: 20MB
      max-file-size: 20MB
logging:
  level:
    root: INFO
    cn.edu.sicnu.dao: debug
#  file: F:\software-contents\intellijIDEA\log\a.log
mybatis:
  mapper-locations: cn/edu/sicnu/mapper/*.xml
  type-aliases-package: cn.edu.sicnu.entity