server:
  servlet:
    context-path: /mangerSys
#  address: 192.168.1.106
jasypt:
  encryptor:
    password: ljk

spring:
  profiles:
    active: prod
  mvc:
    view:
      prefix: /
      suffix: .jsp
#  http:
#    multipart:
#      max-request-size: 20MB
#      max-file-size: 20MB
#logging:
#  level:
#    root: INFO
#    cn.edu.sicnu.dao: debug
#  file: F:\software-contents\intellijIDEA\log\a.log
#mybatis:
#  mapper-locations: cn/edu/sicnu/mapper/*.xml
#  type-aliases-package: cn.edu.sicnu.entity

#logging:
mybatis-plus:
  mapper-locations: cn/edu/sicnu/mapper/*.xml
  type-aliases-package: cn.edu.sicnu.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  config: classpath:log4j.xml
